# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('userC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserProfile')),
            ],
        ),
    ]
