# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_mycircle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycircle',
            name='userC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
