# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20160428_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycircle',
            name='full_name',
            field=models.CharField(default='No_name', max_length=50),
            preserve_default=False,
        ),
    ]
