# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_mycircle_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycircle',
            old_name='full_name',
            new_name='Uname',
        ),
    ]
